import type { Market } from "@/lib/i18n/config";
import { getPublicContact } from "@/lib/public-contact";

export const trustPageSlugs = {
  co: ["contacto", "envios", "devoluciones", "privacidad", "terminos", "pagos", "preguntas-frecuentes"],
  us: ["contact", "shipping", "returns", "privacy", "terms", "payments", "faq"],
} as const;

type TrustSection = { heading: string; paragraphs: string[]; bullets?: string[] };
type TrustPageContent = { key: string; title: string; description: string; sections: TrustSection[] };
export type TrustPage = TrustPageContent & { indexable: boolean };

const contact = getPublicContact();
const incompletePolicyKeys = new Set(["returns", "privacy", "terms"]);

const pages: Record<Market, Record<string, TrustPageContent>> = {
  co: {
    contacto: { key: "contact", title: "Contacto", description: "Canales oficiales para resolver preguntas sobre productos, pagos, envíos y pedidos de Nexora.", sections: [{ heading: "Escríbenos", paragraphs: [`El canal administrativo aprobado de Nexora es ${contact.email}. Incluye la referencia del pedido si ya realizaste una compra; nunca envíes números completos de tarjeta, claves ni códigos de seguridad.`], bullets: [`Correo: ${contact.email}`, `WhatsApp: ${contact.whatsappLabel}`] }, { heading: "Antes de comprar", paragraphs: ["Puedes consultar disponibilidad, estilos y condiciones del producto. El costo y el plazo de envío sólo se muestran después de que CJ Dropshipping devuelve una cotización válida para la dirección elegida."] }] },
    envios: { key: "shipping", title: "Envíos", description: "Cómo Nexora cotiza métodos, costos y tiempos de envío reales de CJ Dropshipping.", sections: [{ heading: "Cotización por destino", paragraphs: ["Nexora solicita país, departamento o estado, ciudad, código postal, dirección, cantidad y estilo exacto. CJ puede ofrecer varios métodos; la tienda marca la opción de menor costo y permite elegir otra disponible."], bullets: ["El envío se suma al total antes de abrir el pago.", "La tarifa tiene vencimiento y debe recalcularse si cambia el carrito o la dirección.", "Los tiempos mostrados proceden de CJ; no son una garantía independiente de Nexora."] }, { heading: "Aduanas y zonas remotas", paragraphs: ["Cuando CJ informa impuestos, trámites aduaneros o recargos de zona remota, la cotización los identifica. Cargos exigidos posteriormente por autoridades del destino pueden corresponder al destinatario según la legislación aplicable."] }] },
    devoluciones: { key: "returns", title: "Devoluciones y reembolsos", description: "Proceso de revisión de devoluciones y reembolsos de Nexora sin promesas no verificadas.", sections: [{ heading: "Solicita una revisión", paragraphs: [`Antes de devolver un artículo, escribe a ${contact.email} con la referencia del pedido, una explicación y evidencia del estado recibido. No envíes el producto a una dirección no confirmada por Nexora.`], bullets: ["La elegibilidad depende del estado del producto, el motivo, la trazabilidad del envío y la normativa aplicable.", "Un pago aprobado no se considera reembolsado hasta que el procesador confirme la devolución.", "Nexora comunicará por correo el resultado y las instrucciones verificadas."] }, { heading: "Información pendiente de aprobación comercial", paragraphs: ["El propietario debe aprobar y publicar plazos, dirección de devolución y quién asume cada costo antes de activar una política estructurada en Merchant Center. Esta página se mantiene fuera del índice hasta completar esos datos."] }] },
    privacidad: { key: "privacy", title: "Privacidad", description: "Información sobre el tratamiento de datos personales, preferencias y medición en Nexora.", sections: [{ heading: "Datos necesarios", paragraphs: ["Para cotizar y procesar un pedido se usan los datos de contacto y entrega que proporciona el cliente. Los datos de tarjeta se ingresan directamente en el procesador de pago y no son recibidos por Nexora."], bullets: ["CJ Dropshipping recibe los datos necesarios para cotizar y preparar el despacho.", "Wompi recibe los datos necesarios para procesar el pago en Colombia.", "El libro privado de ventas registra el pedido y su seguimiento; no se guarda en Git."] }, { heading: "Analítica y consentimiento", paragraphs: ["Las herramientas publicitarias externas permanecen desactivadas hasta que existan identificadores configurados y el visitante otorgue el consentimiento aplicable. Los eventos no deben incluir nombres, correos, direcciones ni datos de pago."], bullets: ["La preferencia de mercado se guarda en una cookie funcional.", "Los parámetros de campaña se conservan localmente con caducidad.", "Puedes retirar el consentimiento de analítica desde el control de privacidad."] }, { heading: "Contacto", paragraphs: [`Para consultas de privacidad escribe a ${contact.email}. La identidad legal y los plazos regulatorios definitivos deben completarse con información aprobada por el propietario.`] }] },
    terminos: { key: "terms", title: "Términos y condiciones", description: "Condiciones generales para navegar y comprar en Nexora.", sections: [{ heading: "Catálogo y disponibilidad", paragraphs: ["Nexora publica únicamente fichas que superan validaciones de imagen, inventario y contenido. Una cotización o un artículo en el carrito no reserva inventario; la disponibilidad vuelve a verificarse antes del cobro cuando corresponde."], bullets: ["No se publican reseñas, descuentos ni beneficios médicos no verificados.", "Las imágenes son recursos oficiales del proveedor y pueden mostrar varios estilos; la selección del cliente determina la referencia del pedido.", "Los precios y condiciones pueden actualizarse de forma versionada, bajo supervisión humana."] }, { heading: "Pedidos", paragraphs: ["El pedido avanza sólo después de una confirmación de pago conciliada. La pantalla de regreso del navegador no sustituye el webhook firmado del procesador." ] }, { heading: "Información legal pendiente", paragraphs: ["Razón social, identificación tributaria y domicilio comercial se publicarán únicamente cuando el propietario entregue y apruebe esos datos. Este texto no los sustituye."] }] },
    pagos: { key: "payments", title: "Métodos de pago", description: "Estado real de los medios de pago disponibles en Nexora por mercado.", sections: [{ heading: "Colombia", paragraphs: ["Cuando las credenciales de producción están completas, Nexora abre el checkout alojado de Wompi en COP. El total firmado incluye productos y los envíos CJ seleccionados. Nexora no recibe la información de tarjeta." ] }, { heading: "Estados Unidos", paragraphs: ["PayPal procesa el checkout alojado en USD únicamente cuando las credenciales Live, el webhook firmado y el libro privado de ventas están configurados y conciliados. Si cualquiera de esos controles falla, Nexora bloquea el cobro y lo informa de forma explícita."] }] },
    "preguntas-frecuentes": { key: "faq", title: "Preguntas frecuentes", description: "Respuestas verificables sobre el catálogo, los envíos y los pagos de Nexora.", sections: [{ heading: "¿Los productos y las imágenes son reales?", paragraphs: ["Sí. Las fichas públicas proceden del catálogo versionado de CJ Dropshipping y utilizan sus imágenes oficiales. Un producto incompleto o no disponible no se sustituye con relleno."] }, { heading: "¿Cuánto cuesta el envío?", paragraphs: ["Depende del estilo, cantidad y dirección. CJ devuelve los métodos disponibles y Nexora suma la opción elegida al total antes de pagar."] }, { heading: "¿Cómo confirmo que pagué?", paragraphs: ["Nexora consulta el estado oficial y concilia el evento firmado del procesador. Conserva el comprobante y revisa el correo; no repitas el pago si aparece pendiente."] }, { heading: "¿Los productos de bienestar tienen fines médicos?", paragraphs: ["No. Nexora los presenta como accesorios generales y no formula promesas de diagnóstico, tratamiento o resultados clínicos."] }] },
  },
  us: {
    contact: { key: "contact", title: "Contact", description: "Official Nexora channels for product, payment, shipping, and order questions.", sections: [{ heading: "Reach us", paragraphs: [`Nexora's approved administrative email is ${contact.email}. Include your order reference when applicable; never send complete card numbers, passwords, or security codes.`], bullets: [`Email: ${contact.email}`, `WhatsApp: ${contact.whatsappLabel}`] }, { heading: "Before ordering", paragraphs: ["You may ask about availability, styles, and product information. Shipping cost and timing are shown only after CJ Dropshipping returns a valid quote for the selected address."] }] },
    shipping: { key: "shipping", title: "Shipping", description: "How Nexora obtains actual CJ Dropshipping methods, costs, and delivery estimates.", sections: [{ heading: "Destination quote", paragraphs: ["Nexora uses the country, state, city, ZIP code, address, quantity, and exact style. CJ may offer multiple methods; the store highlights the lowest-cost option while allowing another available method."], bullets: ["Shipping is included in the total before payment.", "The quote expires and must be refreshed after a cart or address change.", "Displayed timing comes from CJ and is not a separate Nexora guarantee."] }, { heading: "Customs and remote areas", paragraphs: ["When CJ reports taxes, customs processing, or remote-area fees, the quote identifies them. Authorities may impose additional destination charges payable by the recipient under applicable law."] }] },
    returns: { key: "returns", title: "Returns and refunds", description: "Nexora's review process for returns and refunds without unverified promises.", sections: [{ heading: "Request a review", paragraphs: [`Before returning an item, email ${contact.email} with the order reference, explanation, and evidence of the item's received condition. Do not ship to an address that Nexora has not confirmed.`], bullets: ["Eligibility depends on product condition, reason, shipping traceability, and applicable law.", "An approved payment is not refunded until the processor confirms the refund.", "Nexora will provide the verified outcome and instructions by email."] }, { heading: "Commercial approval still required", paragraphs: ["The owner must approve exact time windows, the return address, and responsibility for costs before a structured Merchant Center policy is enabled. This page remains excluded from search indexes until those details are complete."] }] },
    privacy: { key: "privacy", title: "Privacy", description: "How Nexora handles personal information, preferences, and measurement.", sections: [{ heading: "Required information", paragraphs: ["Contact and delivery information provided by the customer is used to quote and process an order. Card details are entered directly with the payment processor and are not received by Nexora."], bullets: ["CJ Dropshipping receives information required to quote and prepare shipment.", "PayPal receives payment details for a configured United States checkout.", "The private sales ledger records order operations and is not stored in Git."] }, { heading: "Analytics and consent", paragraphs: ["External advertising tools remain off until identifiers are configured and the visitor provides applicable consent. Events must never contain names, email addresses, street addresses, or payment details."], bullets: ["A functional cookie stores the market preference.", "Campaign parameters are retained locally with an expiration.", "Analytics consent can be withdrawn through the privacy control."] }, { heading: "Contact", paragraphs: [`Email ${contact.email} with privacy questions. Final legal identity and regulatory response periods require owner-approved information.`] }] },
    terms: { key: "terms", title: "Terms and conditions", description: "General terms for browsing and purchasing from Nexora.", sections: [{ heading: "Catalog and availability", paragraphs: ["Nexora publishes listings that pass image, inventory, and editorial checks. A shipping quote or cart item does not reserve inventory; availability is rechecked before charging when required."], bullets: ["No unverified reviews, discounts, or medical benefits are published.", "Official supplier images may show several styles; the customer's selection determines the ordered reference.", "Prices and terms are updated through versioned, human-supervised changes."] }, { heading: "Orders", paragraphs: ["An order advances only after reliable payment confirmation and reconciliation. A browser redirect does not replace a verified payment webhook."] }, { heading: "Legal information pending", paragraphs: ["Legal entity, tax identifier, and business address will be published only after the owner supplies and approves them. This text does not substitute for those details."] }] },
    payments: { key: "payments", title: "Payment methods", description: "The current state of Nexora payment methods by market.", sections: [{ heading: "United States", paragraphs: ["PayPal hosts the USD checkout only when Live credentials, a signed webhook, and the private sales ledger are configured and reconciled. Nexora blocks charging and explains the configuration state if any control is unavailable."] }, { heading: "Colombia", paragraphs: ["When production credentials are complete, Nexora opens Wompi's hosted checkout in COP. The signed total includes products and selected CJ shipping. Nexora does not receive card details."] }] },
    faq: { key: "faq", title: "Frequently asked questions", description: "Verified answers about Nexora products, shipping, and payments.", sections: [{ heading: "Are the products and images real?", paragraphs: ["Yes. Public listings come from the versioned CJ Dropshipping catalog and use its official images. Incomplete or unavailable items are not replaced with filler content."] }, { heading: "How much is shipping?", paragraphs: ["It depends on style, quantity, and destination. CJ returns available methods and Nexora includes the selected option in the total."] }, { heading: "Can I pay in the United States?", paragraphs: ["When PayPal Live, its signed webhook, and the private order ledger are all available, the checkout opens on PayPal in USD. Nexora blocks the charge if those controls cannot be verified."] }, { heading: "Do wellbeing items make medical claims?", paragraphs: ["No. Nexora presents them as general accessories and does not claim diagnosis, treatment, or clinical outcomes."] }] },
  },
};

export function getTrustPage(market: Market, slug: string) {
  const page = pages[market][slug];
  return page ? { ...page, indexable: !incompletePolicyKeys.has(page.key) } : undefined;
}

export function counterpartTrustSlug(market: Market, slug: string) {
  const page = getTrustPage(market, slug);
  if (!page) return undefined;
  const target: Market = market === "co" ? "us" : "co";
  return Object.entries(pages[target]).find(([, candidate]) => candidate.key === page.key)?.[0];
}
