import { redirect } from "next/navigation";
import { AdminNavigation } from "@/components/admin/admin-navigation";
import { IntelligenceProposalCard } from "@/components/admin/intelligence-proposal-card";
import { isAdmin } from "@/lib/admin-auth";
import { buildIntelligenceSnapshot } from "@/lib/intelligence/engine";
import { logout } from "../actions";

export const dynamic = "force-dynamic";

export default async function AdminIntelligencePage() {
  if (!(await isAdmin())) redirect("/admin/login");
  const snapshot = await buildIntelligenceSnapshot();
  return <main id="page-content" tabIndex={-1} className="min-h-screen px-5 py-6 outline-none sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl">
    <header className="flex flex-col justify-between gap-5 border-b border-silver/15 pb-6 xl:flex-row xl:items-center"><div><p className="text-xs font-bold tracking-[.16em] text-emerald uppercase">Nexora / Dirección de inteligencia</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white">Modo sombra y decisiones supervisadas</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-silver/65">Observa señales reales, argumenta propuestas y conserva su resultado. No modifica precios, catálogo, pagos ni pedidos sin autorización.</p></div><div className="flex flex-wrap items-center gap-3 xl:justify-end"><AdminNavigation current="intelligence" /><form action={logout}><button className="rounded-full border border-silver/25 px-4 py-2 text-sm text-silver/80 hover:border-silver">Cerrar sesión</button></form></div></header>
    <section className="mt-6 grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-emerald/25 bg-emerald/[.06] p-5"><p className="text-sm text-silver/65">Modo operativo</p><p className="mt-2 text-2xl font-semibold text-emerald">Sombra</p><p className="mt-2 text-xs leading-5 text-silver/60">Propone y explica; la decisión es humana.</p></article><article className="rounded-2xl border border-silver/15 bg-white/[.025] p-5"><p className="text-sm text-silver/65">Madurez para autonomía</p><p className="mt-2 text-2xl font-semibold text-white">{snapshot.readiness.scorePercent}%</p><p className="mt-2 text-xs leading-5 text-silver/60">Todos los umbrales deben sostenerse {snapshot.readiness.requiredConsecutiveDays} días.</p></article><article className={`rounded-2xl border p-5 ${snapshot.connected ? "border-emerald/25 bg-emerald/[.04]" : "border-amber-300/25 bg-amber-300/[.05]"}`}><p className="text-sm text-silver/65">Memoria de eventos</p><p className="mt-2 text-2xl font-semibold text-white">{snapshot.connected ? `${snapshot.events.trackedEvents} eventos` : "Pendiente"}</p><p className="mt-2 text-xs leading-5 text-silver/60">{snapshot.connected ? `${snapshot.events.trackedSessions} sesiones anónimas, sin PII.` : "Despliega el Apps Script actualizado para habilitar decisiones y aprendizaje."}</p></article></section>
    <section className="mt-8 rounded-2xl border border-silver/15 bg-white/[.025] p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-semibold text-white">Puertas obligatorias para autonomía futura</h2><p className="mt-1 text-xs leading-5 text-silver/60">La elegibilidad no activa nada: una migración de modo siempre requerirá tu aprobación explícita.</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${snapshot.readiness.eligible ? "bg-emerald/10 text-emerald" : "bg-amber-300/10 text-amber-100"}`}>{snapshot.readiness.eligible ? "Elegible para evaluación humana" : "Aún no elegible"}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{snapshot.readiness.gates.map((gate) => <article key={gate.id} className="rounded-xl border border-silver/10 bg-onyx/40 p-4"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold text-white">{gate.label}</p><span className={gate.met ? "text-emerald" : "text-amber-100"}>{gate.met ? "✓" : "○"}</span></div><p className="mt-3 text-lg font-semibold text-white">{gate.current.toLocaleString("es-CO")} / {gate.target.toLocaleString("es-CO")} {gate.unit}</p><p className="mt-2 text-[11px] leading-4 text-silver/50">{gate.reason}</p></article>)}</div><details className="mt-5"><summary className="cursor-pointer text-xs font-semibold text-silver/70">Acciones que nunca serán autónomas</summary><ul className="mt-3 grid gap-2 text-xs text-silver/60 sm:grid-cols-2">{snapshot.readiness.permanentlyHumanControlled.map((item) => <li key={item}>• {item}</li>)}</ul></details></section>
    <section className="mt-8"><div className="flex items-end justify-between gap-4"><div><h2 className="text-xl font-semibold text-white">Propuestas pendientes y trazables</h2><p className="mt-1 text-xs leading-5 text-silver/60">Cada propuesta expira en siete días; las decisiones quedan en el libro privado.</p></div><span className="rounded-full bg-white/[.05] px-3 py-1 text-xs text-silver/65">{snapshot.proposals.filter((proposal) => proposal.status === "proposed").length} pendientes</span></div><div className="mt-5 grid gap-5">{snapshot.proposals.length ? snapshot.proposals.map((proposal) => <IntelligenceProposalCard key={proposal.id} proposal={proposal} connected={snapshot.connected} />) : <p className="rounded-2xl border border-silver/15 p-5 text-sm text-silver/60">No hay propuestas nuevas. Esto no se interpreta como falta de demanda.</p>}</div></section>
  </div></main>;
}
